# Generated by Django 3.2.25 on 2025-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(default='In Stock', max_length=100),
        ),
    ]
