# Generated by Django 3.2.25 on 2025-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20250206_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amazon_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
