# Generated by Django 3.2.25 on 2025-02-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20250206_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
